version: 2
steps:
    install_dependencies: &install_dependencies
        name: Install Dependencies
        command: haxelib install utest
    package_workspace: &package_workspace
        name: Package Workspace
        command: |
            mkdir workspace/
            cp -r build/ workspace/build/
    persist_workspace: &persist_workspace
        root: workspace
        paths:
            - build
    attach_workspace: &attach_workspace
        at: workspace
    extract_workspace: &extract_workspace
        name: Extract Workspace
        command: |
            cp -r workspace/build/ build/
jobs:
    interpret_test:
        docker:
            - image: haxe:4.0.5
        steps:
            - checkout
            - run:
                <<: *install_dependencies
            - run:
                name: Interpret Tests
                command: haxe interpret-tests.hxml
    compile_tests:
        docker:
            - image: haxe:4.0.5
        steps:
            - checkout
            - run:
                <<: *install_dependencies
            - run:
                name: Compile Tests
                command: haxe compile-tests.hxml
            - run:
                <<: *package_workspace
            - persist_to_workspace:
                <<: *persist_workspace
    neko_test:
        docker:
            - image: haxe:4.0.5
        steps:
            - attach_workspace:
                <<: *attach_workspace
            - run:
                <<: *extract_workspace
            - run:
                name: Run Tests
                command: |
                    neko build/test/neko-test.n
    python_test:
        docker:
            - image: python:3.6.7
        steps:
            - attach_workspace:
                <<: *attach_workspace
            - run:
                <<: *extract_workspace
            - run:
                name: Run Tests
                command: |
                    python build/test/python-test.py
workflows:
    version: 2
    test:
        jobs:
            - interpret_test
            - compile_tests
            - neko_test:
                requires:
                    - interpret_test
                    - compile_tests
            - python_test:
                requires:
                    - interpret_test
                    - compile_tests
