version: 2
jobs:
    build:
        docker:
            - image: haxe:3.4.4
        steps:
            - checkout
            - run:
                name: Install Test Dependencies
                command: |
                    haxelib install munit 2.3.2
                    haxelib install hamcrest 2.0.1
            - run:
                name: Compile Tests
                command: |
                    haxelib run munit gen test/
                    haxe test.hxml
                    neko build/neko_test.n
            - run:
                name: Run Neko Test
                command: |
                    neko build/neko_test.n
    echotest:
        docker:
            - image: haxe:3.4.4
        steps:
            - run:
                name: echo test
                command: |
                    echo test
workflows:
    version: 2
    build_and_echo:
        jobs:
            - build
            - echotest
