version: 2
jobs:
    compile_tests:
        docker:
            - image: haxe:3.4.4
        steps:
            - checkout
            - run:
                name: Install Test Dependencies
                command: |
                    haxelib install munit 2.3.2
                    haxelib install hamcrest 2.0.1
            - run:
                name: Compile Tests
                command: |
                    haxelib run munit gen test/
                    haxe test.hxml
            - run:
                name: Prepare Workspace
                command: |
                    mkdir workspace/
                    cp -r build/ workspace/build/
            - persist_to_workspace:
                root: workspace
                paths:
                    - build
    neko_test:
        docker:
            - image: haxe:3.4.4
        steps:
            - attach_workspace:
                at: workspace
            - run:
                name: Extract Workspace
                command: |
                    cp -r workspace/build/ build/
            - run:
                name: Run Neko Tests
                command: |
                    neko build/neko_test.n
workflows:
    version: 2
    test:
        jobs:
            - compile_tests
            - neko_test:
                requires:
                    - compile_tests
