version: 2
jobs:
    build:
        docker:
            - image: haxe:3.4.4
        steps:
            - checkout
            - run:
                name: Setup Testing
                command: |
                    haxelib install munit 2.3.2
                    haxelib install hamcrest 2.0.1
            - run:
                name: Testing
                command: |
                    haxelib run munit test
# TODO debug test running command, perhaps change to new image via workspace saving and run on python image?
